
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms_db
    username: root
    password: Santosh@416
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
jwt:
  secret: myjwtsecretkey1234567890
